name: cross_tab_example
description: Demonstrates cross_tab.
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cross_tab:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
