name: masonry_kit_example
description: Demonstrates masonry_kit.
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  masonry_kit:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
